# -*- coding: utf-8 -*-
"""Copy of 3_Risk

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDbJC72lHK8Afb_2pfRoYH2izW5vNhdH
"""

import streamlit as st
import pandas as pd
import altair as alt
from pathlib import Path

st.set_page_config(page_title="Risk Analysis (CAPM)", layout="wide")

# GLOBAL TICKER STATE
if "ticker" not in st.session_state:
    st.session_state["ticker"] = "A"

ticker = st.session_state["ticker"]

# COMPANY NAMES
TICKER_NAME_MAP = {
    "A": "Agilent Technologies, Inc.",
    "BIIB": "Biogen Inc.",
    "LLY": "Eli Lilly and Company",
    "JNJ": "Johnson & Johnson",
    # (rest unchanged)
}

st.sidebar.markdown("---")
st.sidebar.markdown(f"### Current ticker: `{ticker}`")


# LOAD DATA
def find_file(filename):
    paths = [
        Path(filename),
        Path("data") / filename,
        Path(__file__).parent.parent / filename,
        Path(__file__).parent.parent / "data" / filename,
    ]
    for p in paths:
        if p.exists():
            return p
    return None


@st.cache_data
def load_capm():
    path = find_file("capm_risk_metrics.csv")
    if path is None:
        raise FileNotFoundError("capm_risk_metrics.csv not found")
    return pd.read_csv(path)


df = load_capm()
row = df[df["ticker"].str.upper() == ticker.upper()].iloc[0]

beta = row["beta"]
alpha = row["alpha"]
r2 = row["r_squared"]
label = row["beta_risk_label"]

# CLASSIFICATION HELPERS
def classify_beta(b):
    if b < 0.9:
        return "defensive"
    elif b > 1.1:
        return "aggressive"
    return "neutral"


def classify_alpha(a):
    if a > 0.001:
        return "positive"
    elif a < -0.001:
        return "negative"
    return "neutral"


def classify_r2(r):
    if r > 0.6:
        return "strong"
    elif r >= 0.3:
        return "moderate"
    return "weak"


beta_case = classify_beta(beta)
alpha_case = classify_alpha(alpha)
r2_case = classify_r2(r2)

# PAGE HEADER
company_name = TICKER_NAME_MAP.get(ticker, "")
display_name = f"{ticker} ({company_name})" if company_name else ticker

st.title("Risk Analysis (CAPM)")
st.markdown(f"### Current ticker: `{display_name}`")

# METRICS
st.markdown("## 1) Key Risk Metrics")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Alpha", f"{alpha:.4f}")
c2.metric("Beta", f"{beta:.3f}")
c3.metric("R-squared", f"{r2:.3f}")
c4.metric("Risk Label", label)

# BETA CHART
st.markdown("## 2) Beta vs Market")

chart_df = pd.DataFrame({
    "Type": ["Company", "Market"],
    "Beta": [beta, 1.0]
})

chart = alt.Chart(chart_df).mark_bar(size=60).encode(
    x="Type",
    y="Beta",
    color=alt.Color("Type", scale=alt.Scale(
        domain=["Company", "Market"],
        range=["#1f77b4", "#9ecae1"]
    )),
)

st.altair_chart(chart, use_container_width=True)

# INTERPRETATION
st.markdown("## 3) Interpretation")

headline = ""
if beta_case == "aggressive" and alpha_case == "negative":
    headline = "Higher market risk without strong risk-adjusted reward"
elif beta_case == "aggressive":
    headline = "Higher market risk with potential upside"
elif beta_case == "defensive":
    headline = "Lower market risk, more stable profile"
else:
    headline = "Market-aligned risk profile"

st.markdown(f"### {headline}")

st.write(
    f"The stock has a beta of {beta:.3f}, indicating its sensitivity to market movements. "
    f"Alpha is {alpha:.4f}, reflecting its risk-adjusted performance, and R² is {r2:.3f}, "
    "which measures how much of its return variation is explained by the market."
)

# KEY TAKEAWAYS
st.markdown("## 4) Key Takeaways")

# Beta takeaway
if beta_case == "aggressive":
    st.markdown("**Higher-than-market risk profile**")
    st.write(
        "The stock carries above-market systematic risk, meaning it is more sensitive to market movements. "
        "Investors should expect larger swings relative to the benchmark."
    )
elif beta_case == "defensive":
    st.markdown("**Lower-than-market risk profile**")
    st.write(
        "The stock carries below-market systematic risk, meaning it tends to be less volatile than the market. "
        "This can provide stability, especially during downturns."
    )
else:
    st.markdown("**Market-aligned risk profile**")
    st.write(
        "The stock’s risk level is close to the market benchmark, suggesting typical sensitivity to market movements."
    )

# Alpha takeaway
if alpha_case == "positive":
    st.markdown("**Strong risk-adjusted performance signal**")
    st.write(
        "Positive alpha suggests the stock has delivered returns above CAPM expectations, indicating efficient use of risk."
    )
elif alpha_case == "negative":
    st.markdown("**Weak risk-adjusted performance signal**")
    st.write(
        "Negative alpha suggests the stock has not sufficiently rewarded investors for the level of risk taken."
    )
else:
    st.markdown("**Neutral performance signal**")
    st.write(
        "Alpha is close to zero, indicating no strong evidence of over- or under-performance relative to risk."
    )

# R2 takeaway
if r2_case == "strong":
    st.markdown("**Strong CAPM explanatory power**")
    st.write(
        "A high R-squared means market movements explain a large portion of the stock’s returns, making CAPM insights more reliable."
    )
elif r2_case == "moderate":
    st.markdown("**Moderate CAPM explanatory power**")
    st.write(
        "Market movements explain some of the stock’s returns, but company-specific factors are also important."
    )
else:
    st.markdown("**Weak CAPM explanatory power**")
    st.write(
        "A low R-squared suggests that firm-specific factors play a larger role, so CAPM should be interpreted cautiously."
    )

# CAPM CONTEXT SECTION
st.markdown("## 5) Risk Interpretation Guide")

st.markdown("**What is CAPM?**")
st.write(
    "The Capital Asset Pricing Model (CAPM) is a framework used to evaluate whether a stock’s return "
    "is appropriate given its level of market risk."
)

st.markdown("**Beta (Market Risk)**")
st.write(
    "Beta measures how sensitive a stock is to market movements. A beta above 1 indicates higher volatility, "
    "while below 1 suggests a more defensive profile."
)

st.markdown("**Alpha (Performance)**")
st.write(
    "Alpha measures whether a stock has outperformed or underperformed relative to its expected return given its risk."
)

st.markdown("**R-squared (Reliability)**")
st.write(
    "R-squared indicates how much of a stock’s return variation is explained by the market. "
    "Higher values suggest CAPM is more informative."
)

st.info(
    "CAPM is a useful benchmark for understanding market risk, but it should always be interpreted alongside "
    "company fundamentals and peer comparisons."
)

st.markdown("## 5) Explore More")
st.markdown(
    """
- **Valuation Assessment:** Review the model’s latest-year valuation result and historical valuation context
- **Risk Analysis:** Examine beta, alpha, and R-squared for the selected company
- **Methodology:** See the project framing, data sources, and modeling context
"""
)
